import React, { useState, useEffect } from 'react';

function CalculatorModule() {
  const [calcSubTab, setCalcSubTab] = useState('mogly');
  
  // --- Mogly Calculator States ---
  const [timeframe, setTimeframe] = useState('intraday');
  const [ltpInput, setLtpInput] = useState('');
  const [resultData, setResultData] = useState(null);
  const [copyBtnText, setCopyBtnText] = useState('📋 Copy Levels');
  const [copyBtnBg, setCopyBtnBg] = useState('#475569');

  // --- Spiral Calculator States ---
  const [highVal, setHighVal] = useState('24089.80');
  const [lowVal, setLowVal] = useState('23858.25');
  const [spiralData, setSpiralData] = useState({
    hRoot: '-',
    lRoot: '-',
    rDiff: '-',
    pRange: '-',
    mPrice: '-',
    gates: []
  });
  const [spiralCopyText, setSpiralCopyText] = useState('📋 Copy Result');
  const [spiralCopyBg, setSpiralCopyBg] = useState('#8b5a2b');

  // --- Mogly Logic ---
  const calculateGann = () => {
    let ltp = parseFloat(ltpInput);
    if (isNaN(ltp) || ltp <= 0) {
      alert("Please enter a valid price");
      return;
    }

    let root = Math.sqrt(ltp);
    let baseRoot = Math.floor(root * 8) / 8;
    
    let buyEntry = Math.pow(baseRoot + 0.125, 2);
    let sellEntry = Math.pow(baseRoot, 2);
    
    let step1, step2, step3, step4;
    if (timeframe === 'intraday') {
      step1 = 0.10; step2 = 0.225; step3 = 0.350; step4 = 0.475;
    } else if (timeframe === 'weekly') {
      step1 = 0.25; step2 = 0.50; step3 = 0.75; step4 = 1.00;
    } else if (timeframe === 'monthly') {
      step1 = 0.50; step2 = 1.00; step3 = 1.50; step4 = 2.00;
    }
    
    let bT1 = Math.pow(Math.sqrt(buyEntry) + step1, 2);
    let bT2 = Math.pow(Math.sqrt(buyEntry) + step2, 2);
    let bT3 = Math.pow(Math.sqrt(buyEntry) + step3, 2);
    let bT4 = Math.pow(Math.sqrt(buyEntry) + step4, 2);
    
    let sT1 = Math.pow(Math.sqrt(sellEntry) - step1, 2);
    let sT2 = Math.pow(Math.sqrt(sellEntry) - step2, 2);
    let sT3 = Math.pow(Math.sqrt(sellEntry) - step3, 2);
    let sT4 = Math.pow(Math.sqrt(sellEntry) - step4, 2);

    setResultData({
      buyPrice: buyEntry.toFixed(2),
      sellPrice: sellEntry.toFixed(2),
      buySl: sellEntry.toFixed(2),
      sellSl: buyEntry.toFixed(2),
      buyTargets: [bT1.toFixed(2), bT2.toFixed(2), bT3.toFixed(2), bT4.toFixed(2)],
      sellTargets: [sT1.toFixed(2), sT2.toFixed(2), sT3.toFixed(2), sT4.toFixed(2)]
    });
  };

  const clearFields = () => {
    setLtpInput('');
    setResultData(null);
  };

  const copyLevels = () => {
    if (!resultData) return;
    let timeframeText = timeframe === 'intraday' ? 'Intraday (Small Targets)' : timeframe === 'weekly' ? 'Weekly (Medium Positional)' : 'Monthly (Big Monthly Targets)';
    let buyTargetsText = resultData.buyTargets.map((t, idx) => `T${idx+1}: ${t}`).join(' | ');
    let sellTargetsText = resultData.sellTargets.map((t, idx) => `T${idx+1}: ${t}`).join(' | ');

    let textToCopy = `📊 *Gheewala Pro Levels* 📊\n` +
                     `━━━━━━━━━━━━━━━━━━\n` +
                     `🔹 *Type:* ${timeframeText}\n` +
                     `🔹 *LTP:* ${ltpInput}\n\n` +
                     `🐂 *BULLISH / BUY at/above:* ${resultData.buyPrice}\n` +
                     `🎯 *Targets:* ${buyTargetsText}\n` +
                     `🛑 *SL:* ${resultData.buySl}\n\n` +
                     `🐻 *BEARISH / SELL at/below:* ${resultData.sellPrice}\n` +
                     `🎯 *Targets:* ${sellTargetsText}\n` +
                     `🛑 *SL:* ${resultData.sellSl}\n` +
                     `━━━━━━━━━━━━━━━━━━\n` +
                     `_Generated by Gheewala Calculator_`;

    navigator.clipboard.writeText(textToCopy).then(() => {
      setCopyBtnText("✓ Copied!");
      setCopyBtnBg("#22c55e");
      setTimeout(() => {
        setCopyBtnText("📋 Copy Levels");
        setCopyBtnBg("#475569");
      }, 2000);
    });
  };

  // --- Spiral Logic ---
  const calcSpiral = () => {
    try {
      var rawH = highVal.toString().replace(/,/g, '');
      var rawL = lowVal.toString().replace(/,/g, '');
      var h = parseFloat(rawH);
      var l = parseFloat(rawL);

      if (isNaN(h) || isNaN(l) || h <= 0 || l <= 0) return;

      var hRoot = Math.sqrt(h);
      var lRoot = Math.sqrt(l);
      var rDiff = hRoot - lRoot;
      var pRange = h - l;
      var mPrice = (h + l) / 2;

      var rawGates = [
        { deg: "45°", name: "Minor Reaction", angle: 45 },
        { deg: "90°", name: "Quarter Square (Entry Confirm)", angle: 90 },
        { deg: "135°", name: "Mid-Cycle Gate", angle: 135 },
        { deg: "180°", name: "Opposition Gate (Major Swing)", angle: 180 },
        { deg: "225°", name: "Expansion Gate", angle: 225 },
        { deg: "270°", name: "Three-Quarter Square", angle: 270 },
        { deg: "315°", name: "Pre-Full Square Gate", angle: 315 },
        { deg: "360°", name: "Full Square (Cycle Complete)", angle: 360 }
      ];

      var calculatedGates = rawGates.map(g => {
        var factor = g.angle / 180.0;
        var lowUp = Math.pow(lRoot + factor, 2);
        var highDown = Math.pow(hRoot - factor, 2);
        return {
          deg: g.deg,
          name: g.name,
          bullish: lowUp.toFixed(2),
          bearish: highDown.toFixed(2)
        };
      });

      setSpiralData({
        hRoot: hRoot.toFixed(4),
        lRoot: lRoot.toFixed(4),
        rDiff: rDiff.toFixed(4),
        pRange: pRange.toFixed(2),
        mPrice: mPrice.toFixed(2),
        gates: calculatedGates
      });
    } catch (e) {
      console.error(e);
    }
  };

  useEffect(() => {
    calcSpiral();
  }, [highVal, lowVal]);

  const copySpiralResult = () => {
    var bullishText = `🟢 BULLISH TARGETS (From Low):\n`;
    var bearishText = `🔴 BEARISH SUPPORTS (From High):\n`;

    spiralData.gates.forEach(g => {
      bullishText += `${g.deg} -> ${g.bullish}\n`;
      bearishText += `${g.deg} -> ${g.bearish}\n`;
    });

    var textToCopy = `📐 WD Gann's Spiral Root Analysis\n` +
                     `High: ${highVal} | Low: ${lowVal}\n\n` +
                     `--- Root Values ---\n` +
                     `High Root: ${spiralData.hRoot}\n` +
                     `Low Root: ${spiralData.lRoot}\n` +
                     `Root Diff: ${spiralData.rDiff}\n` +
                     `Price Range: ${spiralData.pRange}\n` +
                     `Mid Price: ${spiralData.mPrice}\n\n` +
                     bullishText + `\n` + bearishText;

    navigator.clipboard.writeText(textToCopy).then(() => {
      setSpiralCopyText('✅ Copied Result!');
      setSpiralCopyBg('#2e7d32');
      setTimeout(() => {
        setSpiralCopyText('📋 Copy Result');
        setSpiralCopyBg('#8b5a2b');
      }, 2000);
    });
  };

  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', background: 'white', padding: '24px', borderRadius: '20px', boxShadow: '0px 10px 30px rgba(0,0,0,0.08)' }}>
      
      {/* 🌟 ઉપરના બે બટનો (Mogly & Spiral) */}
      <div style={{ display: 'flex', gap: '10px', marginBottom: '20px', borderBottom: '2px solid #e2e8f0', paddingBottom: '12px' }}>
        <button 
          onClick={() => setCalcSubTab('mogly')} 
          style={{
            flex: 1,
            padding: '12px',
            backgroundColor: calcSubTab === 'mogly' ? '#0288d1' : '#f1f5f9',
            color: calcSubTab === 'mogly' ? '#ffffff' : '#334155',
            border: 'none',
            borderRadius: '12px',
            fontWeight: 'bold',
            cursor: 'pointer',
            fontSize: '15px'
          }}
        >
          📊 Mogly Calculator
        </button>

        <button 
          onClick={() => setCalcSubTab('spiral')} 
          style={{
            flex: 1,
            padding: '12px',
            backgroundColor: calcSubTab === 'spiral' ? '#8b5a2b' : '#f1f5f9',
            color: calcSubTab === 'spiral' ? '#ffffff' : '#334155',
            border: 'none',
            borderRadius: '12px',
            fontWeight: 'bold',
            cursor: 'pointer',
            fontSize: '15px'
          }}
        >
          🌀 Spiral Calculator
        </button>
      </div>

      {/* 🚀 Mogly Tab Content */}
      {calcSubTab === 'mogly' && (
        <div>
          <h2 style={{ textAlign: 'center', color: '#0288d1', fontSize: '26px', marginBottom: '4px', fontWeight: '700' }}>Gheewala Pro</h2>
          <h4 style={{ textAlign: 'center', color: '#64748b', marginBottom: '24px', fontSize: '13px', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '1px' }}>(Multi-Timeframe)</h4>
          
          <label style={{ fontSize: '14px', fontWeight: '600', color: '#475569', display: 'block', marginBottom: '8px' }}>Select Trading Type</label>
          <select 
            value={timeframe} 
            onChange={(e) => setTimeframe(e.target.value)}
            style={{ width: '100%', padding: '14px', marginBottom: '18px', border: '2px solid #e2e8f0', borderRadius: '12px', fontSize: '16px', fontWeight: '600', backgroundColor: '#f8fafc', outline: 'none' }}
          >
            <option value="intraday">Intraday (Small Targets)</option>
            <option value="weekly">Weekly (Medium Positional)</option>
            <option value="monthly">Monthly (Big Monthly Targets)</option>
          </select>

          <label style={{ fontSize: '14px', fontWeight: '600', color: '#475569', display: 'block', marginBottom: '8px' }}>Enter Live Market Price (LTP)</label>
          <input 
            type="number" 
            value={ltpInput} 
            onChange={(e) => setLtpInput(e.target.value)} 
            placeholder="e.g. 1320" 
            step="any" 
            onKeyDown={(e) => { if(e.key === 'Enter') calculateGann(); }}
            style={{ width: '100%', padding: '14px', marginBottom: '18px', border: '2px solid #e2e8f0', borderRadius: '12px', fontSize: '20px', fontWeight: '700', textAlign: 'center', backgroundColor: '#f8fafc', outline: 'none' }} 
          />
          
          <div style={{ display: 'flex', gap: '10px', marginBottom: '5px' }}>
            <button 
              onClick={calculateGann}
              style={{ flex: 2, backgroundColor: '#0288d1', color: 'white', padding: '16px', border: 'none', borderRadius: '12px', fontSize: '16px', cursor: 'pointer', fontWeight: 'bold' }}
            >
              Find Levels
            </button>
            <button 
              onClick={clearFields}
              style={{ flex: 1, backgroundColor: '#e2e8f0', color: '#475569', padding: '16px', border: 'none', borderRadius: '12px', fontSize: '16px', cursor: 'pointer', fontWeight: 'bold' }}
            >
              Clear
            </button>
          </div>

          {resultData && (
            <div style={{ marginTop: '24px' }}>
              <div style={{ padding: '18px', borderRadius: '14px', marginBottom: '16px', backgroundColor: '#f0fdf4', borderLeft: '6px solid #22c55e', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
                <span style={{ color: '#166534', fontWeight: '700', fontSize: '17px' }}>Buy at / above:</span>
                <span style={{ fontWeight: '700', fontSize: '18px', color: '#0f172a', marginLeft: '4px' }}>{resultData.buyPrice}</span><br/>
                <strong style={{ fontSize: '14px', color: '#334155', display: 'block', marginTop: '8px' }}>Targets:</strong>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px', margin: '6px 0' }}>
                  {resultData.buyTargets.map((t, i) => (
                    <span key={i} style={{ padding: '4px 10px', borderRadius: '6px', fontWeight: '700', fontSize: '14px', backgroundColor: '#dcfce7', color: '#166534' }}>
                      T{i+1}: {t}
                    </span>
                  ))}
                </div>
                <strong style={{ fontSize: '14px', color: '#334155' }}>Stoploss (SL):</strong>
                <span style={{ fontWeight: '700', fontSize: '16px', color: '#bc1c1c', marginLeft: '4px' }}>{resultData.buySl}</span>
              </div>
              
              <div style={{ padding: '18px', borderRadius: '14px', marginBottom: '16px', backgroundColor: '#fef2f2', borderLeft: '6px solid #ef4444', boxShadow: '0 4px 12px rgba(0,0,0,0.03)' }}>
                <span style={{ color: '#991b1b', fontWeight: '700', fontSize: '17px' }}>Sell at / below:</span>
                <span style={{ fontWeight: '700', fontSize: '18px', color: '#0f172a', marginLeft: '4px' }}>{resultData.sellPrice}</span><br/>
                <strong style={{ fontSize: '14px', color: '#334155', display: 'block', marginTop: '8px' }}>Targets:</strong>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px', margin: '6px 0' }}>
                  {resultData.sellTargets.map((t, i) => (
                    <span key={i} style={{ padding: '4px 10px', borderRadius: '6px', fontWeight: '700', fontSize: '14px', backgroundColor: '#fee2e2', color: '#991b1b' }}>
                      T{i+1}: {t}
                    </span>
                  ))}
                </div>
                <strong style={{ fontSize: '14px', color: '#334155' }}>Stoploss (SL):</strong>
                <span style={{ fontWeight: '700', fontSize: '16px', color: '#166534', marginLeft: '4px' }}>{resultData.sellSl}</span>
              </div>

              <button 
                onClick={copyLevels}
                style={{ width: '100%', backgroundColor: copyBtnBg, color: 'white', padding: '16px', border: 'none', borderRadius: '12px', fontSize: '16px', cursor: 'pointer', fontWeight: 'bold' }}
              >
                {copyBtnText}
              </button>
            </div>
          )}
        </div>
      )}

      {/* 🌀 Spiral Tab Content */}
      {calcSubTab === 'spiral' && (
        <div style={{ backgroundColor: '#f7f3ed', padding: '15px', borderRadius: '12px', color: '#3d3229' }}>
          
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '2px solid #e6dfd5', paddingBottom: '10px', marginBottom: '20px' }}>
            <div style={{ fontSize: '18px', fontWeight: 'bold', color: '#8b5a2b' }}>📐 WD Gann's Spiral Root Mapping</div>
          </div>

          {/* Input Desk */}
          <div style={{ background: '#ffffff', padding: '20px', borderRadius: '8px', border: '1px solid #e6dfd5', marginBottom: '20px' }}>
            <h3 style={{ margin: '0 0 10px 0', color: '#8b5a2b', fontSize: '15px' }}>INPUT DESK</h3>
            
            <label style={{ fontSize: '12px', fontWeight: 'bold', display: 'block', marginTop: '10px', color: '#3d3229' }}>SWING HIGH PRICE</label>
            <input type="text" value={highVal} onChange={(e) => setHighVal(e.target.value)} style={{ width: '100%', padding: '10px', marginTop: '5px', border: '1px solid #dcd6ce', borderRadius: '5px', fontSize: '15px', background: '#faf8f5', boxSizing: 'border-box', outline: 'none' }} />

            <label style={{ fontSize: '12px', fontWeight: 'bold', display: 'block', marginTop: '10px', color: '#3d3229' }}>SWING LOW PRICE</label>
            <input type="text" value={lowVal} onChange={(e) => setLowVal(e.target.value)} style={{ width: '100%', padding: '10px', marginTop: '5px', border: '1px solid #dcd6ce', borderRadius: '5px', fontSize: '15px', background: '#faf8f5', boxSizing: 'border-box', outline: 'none' }} />
          </div>

          {/* Root Dashboard */}
          <div style={{ background: '#ffffff', padding: '20px', borderRadius: '8px', border: '1px solid #e6dfd5', marginBottom: '20px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '15px' }}>
              <h3 style={{ margin: 0, color: '#8b5a2b', fontSize: '15px' }}>ROOT PRICE DASHBOARD</h3>
              <button onClick={copySpiralResult} style={{ background: spiralCopyBg, color: 'white', border: 'none', padding: '8px 14px', borderRadius: '6px', fontSize: '13px', fontWeight: 'bold', cursor: 'pointer' }}>{spiralCopyText}</button>
            </div>
            <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
              <div style={{ flex: 1, minWidth: '100px', background: '#faf8f5', padding: '10px', textAlign: 'center', borderRadius: '6px', border: '1px solid #e6dfd5' }}><div style={{ fontSize: '10px', color: '#7a6e65', fontWeight: 'bold' }}>HIGH ROOT</div><div style={{ fontSize: '15px', fontWeight: 'bold', color: '#8b5a2b', marginTop: '4px' }}>{spiralData.hRoot}</div></div>
              <div style={{ flex: 1, minWidth: '100px', background: '#faf8f5', padding: '10px', textAlign: 'center', borderRadius: '6px', border: '1px solid #e6dfd5' }}><div style={{ fontSize: '10px', color: '#7a6e65', fontWeight: 'bold' }}>LOW ROOT</div><div style={{ fontSize: '15px', fontWeight: 'bold', color: '#8b5a2b', marginTop: '4px' }}>{spiralData.lRoot}</div></div>
              <div style={{ flex: 1, minWidth: '100px', background: '#faf8f5', padding: '10px', textAlign: 'center', borderRadius: '6px', border: '1px solid #e6dfd5' }}><div style={{ fontSize: '10px', color: '#7a6e65', fontWeight: 'bold' }}>ROOT DIFF</div><div style={{ fontSize: '15px', fontWeight: 'bold', color: '#8b5a2b', marginTop: '4px' }}>{spiralData.rDiff}</div></div>
              <div style={{ flex: 1, minWidth: '100px', background: '#faf8f5', padding: '10px', textAlign: 'center', borderRadius: '6px', border: '1px solid #e6dfd5' }}><div style={{ fontSize: '10px', color: '#7a6e65', fontWeight: 'bold' }}>PRICE RANGE</div><div style={{ fontSize: '15px', fontWeight: 'bold', color: '#8b5a2b', marginTop: '4px' }}>{spiralData.pRange}</div></div>
              <div style={{ flex: 1, minWidth: '100px', background: '#faf8f5', padding: '10px', textAlign: 'center', borderRadius: '6px', border: '1px solid #e6dfd5' }}><div style={{ fontSize: '10px', color: '#7a6e65', fontWeight: 'bold' }}>MID PRICE</div><div style={{ fontSize: '15px', fontWeight: 'bold', color: '#8b5a2b', marginTop: '4px' }}>{spiralData.mPrice}</div></div>
            </div>
          </div>

          {/* Gann Gates Table */}
          <div style={{ background: '#ffffff', padding: '20px', borderRadius: '8px', border: '1px solid #e6dfd5' }}>
            <h3 style={{ margin: '0 0 10px 0', color: '#8b5a2b', fontSize: '15px' }}>IMPORTANT GANN GATES (TARGETS & SUPPORTS)</h3>
            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                <thead>
                  <tr style={{ background: '#f0eae1' }}>
                    <th style={{ border: '1px solid #e6dfd5', padding: '10px', textAlign: 'left', fontSize: '12px' }}>Gate Degree</th>
                    <th style={{ border: '1px solid #e6dfd5', padding: '10px', textAlign: 'left', fontSize: '12px' }}>Gate Name</th>
                    <th style={{ border: '1px solid #e6dfd5', padding: '10px', textAlign: 'left', fontSize: '12px' }}>Bullish Target (From Low)</th>
                    <th style={{ border: '1px solid #e6dfd5', padding: '10px', textAlign: 'left', fontSize: '12px' }}>Bearish Support (From High)</th>
                  </tr>
                </thead>
                <tbody>
                  {spiralData.gates.map((g, idx) => (
                    <tr key={idx}>
                      <td style={{ border: '1px solid #e6dfd5', padding: '10px', fontSize: '12px' }}><b>{g.deg}</b></td>
                      <td style={{ border: '1px solid #e6dfd5', padding: '10px', fontSize: '12px' }}>{g.name}</td>
                      <td style={{ border: '1px solid #e6dfd5', padding: '10px', fontSize: '12px', background: '#e8f5e9', color: '#2e7d32', fontWeight: 'bold' }}>{g.bullish}</td>
                      <td style={{ border: '1px solid #e6dfd5', padding: '10px', fontSize: '12px', background: '#ffebee', color: '#c62828', fontWeight: 'bold' }}>{g.bearish}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

        </div>
      )}

    </div>
  );
}

export default CalculatorModule;
